### ISSUE TITLE
social pollen count site down?

### ISSUE THREAD

**Issue by Wahala** [kylegordon/pypollen#5]
I'm trying to use pypollen on a raspberry pi, I've installed it as instructed and I'm trying by using the example script:
`from pypollen import Pollen
print Pollen(51.7546407,-1.2510746).pollencount`

I saved it in a .py file and when I run it I get a time out error
`pi@raspberrypi:~ $ python pypollentest.py
socialpollencount.co.uk timed out
Traceback (most recent call last):
  File "pypollentest.py", line 2, in <module>
    print Pollen(51.7546407,-1.2510746).pollencount
  File "/home/pi/.local/lib/python2.7/site-packages/pypollen/__init__.py", line 27, in pollencount
    raise RuntimeError("timeout")
RuntimeError: timeout`

trying to access the web address in __init__.py it looks like it may be offline, can anyone confirm?
https://socialpollencount.co.uk/api/forecast?location=

**Comment by kylegordon** [comment]
Looks like it's certainly down. Have asked Benadryl on Twitter about it

**Comment by ad3rinto** [comment]
Hi, the site is still down.
Is this site no longer available? Did you get any feedback from Benadryl via twitter when you requested @kylegordon 
Thanks
